Add make exec to the Makefile, fix a bunch of scripts on the simuPOP online cookbook

diff --git a/web/trunk/Makefile b/web/trunk/Makefile
--- a/web/trunk/Makefile
+++ b/web/trunk/Makefile
@@ -12,3 +12,39 @@ diff:
 		echo "No difference";\
 	fi
 
+exec:
+	for dir in `ls -d persistent/cookbook/uploads/Cookbook/*`;\
+	do \
+		for file in `ls $$dir/*.py`; \
+		do \
+			echo;\
+			echo;\
+			echo;\
+			SIMUGUI=False; SIMUDEBUG=DBG_BATCHTESTING; export SIMUGUI SIMUDEBUG; \
+			grep BATCHTESTING $$file; \
+			if [ "$$?" -ne "0" ]; \
+			then \
+				echo "Running $$file"; \
+				python $$file; \
+			else \
+				OPTION="`grep BATCHTESTING $$file`"; \
+				OPTION=`expr substr "$$OPTION" 15 1000`; \
+				if [ "$$OPTION" == "SKIP" ]; \
+				then \
+					echo; \
+					echo; \
+				    echo "Skipping testing $$file"; \
+					echo; \
+				else \
+					echo "Running $$file $$OPTION"; \
+				    python $$file $$OPTION; \
+				fi; \
+			fi; \
+			if [ "$$?" -ne "0" ]; \
+			then \
+				echo "Execution of $$file failed. Please modify it."; \
+				exit 0; \
+			fi; \
+		done; \
+	done
+
